### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [azimut/somecepl#1]
Can you please expand your README.md on this repo?

**Comment by azimut** [comment]
Hi, done, that was long overdue. Feel free to re-open or ask questions. Btw, kudos for the integration of so many interesting topics on Lisp(!) in biochat. Will review it one day.

**Comment by Bohdan-Khomtchouk** [comment]
Thanks!  Do you have an email address I can reach you at?

**Comment by azimut** [comment]
@Bohdan-Khomtchouk  Sure, you can reach me here or at:
azimut.github at protonmail.com
